module.exports = {
  chainID: 'columbus-5',
  lcd: 'https://terra-classic-lcd.publicnode.com',
  gasAdjustment: 5,
  gasPrices: {
    uluna: 28.325,
    usdr: 0.52469,
    uusd: 0.75,
    ukrw: 850.0,
    umnt: 2142.855,
    ueur: 0.625,
    ucny: 4.9,
    ujpy: 81.85,
    ugbp: 0.55,
    uinr: 54.4,
    ucad: 0.95,
    uchf: 0.7,
    uaud: 0.95,
    usgd: 1.0,
    uthb: 23.1,
    usek: 6.25,
    unok: 6.25,
    udkk: 4.5,
    uidr: 10900.0,
    uphp: 38.0,
    uhkd: 5.85,
    umyr: 3.0,
    utwd: 20.0,
  },
  prefix: 'terra',
  coinType: '330',
  baseAsset: 'uluna',
  name: 'Terra Classic',
  icon: 'https://assets.terra.money/icon/svg/TerraClassic.svg',
  isClassic: true,
  explorer: {
    address: 'https://finder.terra.money/classic/address/{}',
    tx: 'https://finder.terra.money/classic/tx/{}',
    validator: 'https://finder.terra.money/classic/validator/{}',
    block: 'https://finder.terra.money/classic/block/{}',
  },
  tokens: [
    {
      token: 'uaud',
      symbol: 'AUTC',
      name: 'TerraAUD Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/AUT.svg',
      decimals: 6,
    },
    {
      token: 'ucad',
      symbol: 'CATC',
      name: 'TerraCAD Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/CAT.svg',
      decimals: 6,
    },
    {
      token: 'uchf',
      symbol: 'CHTC',
      name: 'TerraCHF Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/CHT.svg',
      decimals: 6,
    },
    {
      token: 'ucny',
      symbol: 'CNTC',
      name: 'TerraCNY Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/CNT.svg',
      decimals: 6,
    },
    {
      token: 'udkk',
      symbol: 'DKTC',
      name: 'TerraDKK Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/DKT.svg',
      decimals: 6,
    },
    {
      token: 'ueur',
      symbol: 'EUTC',
      name: 'TerraEUR Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/EUT.svg',
      decimals: 6,
    },
    {
      token: 'ugbp',
      symbol: 'GPTC',
      name: 'TerraGBP Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/GBT.svg',
      decimals: 6,
    },
    {
      token: 'uhkd',
      symbol: 'HKTC',
      name: 'TerraHKD Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/HKT.svg',
      decimals: 6,
    },
    {
      token: 'uidr',
      symbol: 'IDTC',
      name: 'TerraIDR Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/IDT.svg',
      decimals: 6,
    },
    {
      token: 'uinr',
      symbol: 'INTC',
      name: 'TerraINR Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/INT.svg',
      decimals: 6,
    },
    {
      token: 'ujpy',
      symbol: 'JPTC',
      name: 'TerraJPY Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/JPT.svg',
      decimals: 6,
    },
    {
      token: 'ukrw',
      symbol: 'KRTC',
      name: 'TerraKRW Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/KRT.svg',
      decimals: 6,
    },
    {
      token: 'uluna',
      symbol: 'LUNC',
      name: 'Luna Classic',
      icon: 'https://assets.terra.money/icon/svg/LUNC.svg',
      decimals: 6,
    },
    {
      token: 'umnt',
      symbol: 'UMNTC',
      name: 'TerraMNT Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/MNT.svg',
      decimals: 6,
    },
    {
      token: 'umyr',
      symbol: 'MYTC',
      name: 'TerraMYR Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/MYT.svg',
      decimals: 6,
    },
    {
      token: 'unok',
      symbol: 'NOTC',
      name: 'TerraNOK Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/NOT.svg',
      decimals: 6,
    },
    {
      token: 'uphp',
      symbol: 'PHTC',
      name: 'TerraPHP Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/PHT.svg',
      decimals: 6,
    },
    {
      token: 'usdr',
      symbol: 'SDRC',
      name: 'TerraSDR Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/SDT.svg',
      decimals: 6,
    },
    {
      token: 'usek',
      symbol: 'SETC',
      name: 'TerraSEK Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/SET.svg',
      decimals: 6,
    },
    {
      token: 'usgd',
      symbol: 'SGTC',
      name: 'TerraSGD Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/SGT.svg',
      decimals: 6,
    },
    {
      token: 'uthb',
      symbol: 'THTC',
      name: 'TerraTHB Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/THT.svg',
      decimals: 6,
    },
    {
      token: 'utwd',
      symbol: 'TWTC',
      name: 'TerraTWD Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/TWT.svg',
      decimals: 6,
    },
    {
      token: 'uusd',
      symbol: 'USTC',
      name: 'TerraUSD Classic',
      icon: 'https://assets.terra.money/icon/svg/Terra/UST.svg',
      decimals: 6,
    },
  ],
}
