module.exports = {
  chainID: "axelar-dojo-1",
  lcd: "https://lcd-axelar.imperator.co",
  gasAdjustment: 1.75,
  gasPrices: { uaxl: 0.007 },
  prefix: "axelar",
  coinType: "118",
  baseAsset: "uaxl",
  name: "Axelar",
  icon: "https://station-assets.terra.money/img/chains/Axelar.svg",
  ibc: {
    fromTerra: "channel-6",
    toTerra: "channel-11",
  },
  explorer: {
    address: "https://www.mintscan.io/axelar/account/{}",
    tx: "https://www.mintscan.io/axelar/txs/{}",
    validator: "https://www.mintscan.io/axelar/validators/{}",
    block: "https://www.mintscan.io/axelar/blocks/id/{}",
  },
  tokens: [
    {
      token: "uaxl",
      symbol: "AXL",
      name: "Axelar",
      icon: "https://station-assets.terra.money/img/coins/Axelar.svg",
      decimals: 6,
    },
    {
      token: "aave-wei",
      symbol: "axlAAVE",
      name: "Axelar AAVE",
      icon: "https://station-assets.terra.money/img/coins/axlAAVE.svg",
      decimals: 18,
      isAxelar: true,
    },
    {
      token: "link-wei",
      symbol: "axlLINK",
      name: "Axelar ChainLink",
      icon: "https://station-assets.terra.money/img/coins/axlLINK.svg",
      decimals: 18,
      isAxelar: true,
    },
    {
      token: "dai-wei",
      symbol: "axlDAI",
      name: "Axelar DAI",
      icon: "https://station-assets.terra.money/img/coins/axlDAI.svg",
      decimals: 18,
      isAxelar: true,
    },
    {
      token: "frax-wei",
      symbol: "axlFRAX",
      name: "Axelar Frax",
      icon: "https://station-assets.terra.money/img/coins/axlFRAX.svg",
      decimals: 18,
      isAxelar: true,
    },
    {
      token: "wmatic-wei",
      symbol: "axlMATIC",
      name: "Axelar Matic",
      icon: "https://station-assets.terra.money/img/coins/axlMATIC.svg",
      decimals: 18,
      isAxelar: true,
    },
    {
      token: "uni-wei",
      symbol: "axlUNI",
      name: "Axelar Uniswap",
      icon: "https://station-assets.terra.money/img/coins/axlUNI.svg",
      decimals: 18,
      isAxelar: true,
    },
    {
      token: "uusdc",
      symbol: "axlUSDC",
      name: "Axelar USD Coin",
      icon: "https://station-assets.terra.money/img/coins/axlUSDC.svg",
      isAxelar: true,
    },
    {
      token: "uusdt",
      symbol: "axlUSDT",
      name: "Axelar USD Tether",
      icon: "https://station-assets.terra.money/img/coins/axlUSDT.svg",
      isAxelar: true,
    },
    {
      token: "wbtc-satoshi",
      symbol: "axlWBTC",
      name: "Axelar Wrapped Bitcoin",
      icon: "https://station-assets.terra.money/img/coins/axlWBTC.svg",
      decimals: 8,
      isAxelar: true,
    },
    {
      token: "weth-wei",
      symbol: "axlWETH",
      name: "Axelar Wrapped Ethereum",
      icon: "https://station-assets.terra.money/img/coins/axlETH.svg",
      decimals: 18,
      isAxelar: true,
    },
  ],
};
