module.exports = {
  chainID: 'axelar-dojo-1',
  lcd: 'https://lcd-axelar.imperator.co',
  gasAdjustment: 1.75,
  gasPrices: { uaxl: 0.007 },
  prefix: 'axelar',
  coinType: '118',
  baseAsset: 'uaxl',
  name: 'Axelar',
  icon: 'https://station-assets.terra.money/img/chains/Axelar.svg',
  ibc: {
    fromTerra: 'channel-6',
    toTerra: 'channel-11',
  },
  explorer: {
    address: 'https://www.mintscan.io/axelar/account/{}',
    tx: 'https://www.mintscan.io/axelar/txs/{}',
    validator: 'https://www.mintscan.io/axelar/validators/{}',
    block: 'https://www.mintscan.io/axelar/blocks/id/{}',
  },
  tokens: [
    {
      token: 'uaxl',
      symbol: 'AXL',
      name: 'Axelar',
      icon: 'https://station-assets.terra.money/img/coins/Axelar.svg',
      decimals: 6,
    },
    {
      token: 'aave-wei',
      symbol: 'axlAAVE',
      name: 'Axelar AAVE',
      icon: 'https://station-assets.terra.money/img/coins/axlAAVE.svg',
      decimals: 18,
      isAxelar: true,
    },
    {
      token: 'link-wei',
      symbol: 'axlLINK',
      name: 'Axelar ChainLink',
      icon: 'https://station-assets.terra.money/img/coins/axlLINK.svg',
      decimals: 18,
      isAxelar: true,
    },
    {
      token: 'dai-wei',
      symbol: 'axlDAI',
      name: 'Axelar DAI',
      icon: 'https://station-assets.terra.money/img/coins/axlDAI.svg',
      decimals: 18,
      isAxelar: true,
    },
    {
      token: 'frax-wei',
      symbol: 'axlFRAX',
      name: 'Axelar Frax',
      icon: 'https://station-assets.terra.money/img/coins/axlFRAX.svg',
      decimals: 18,
      isAxelar: true,
    },
    {
      token: 'wmatic-wei',
      symbol: 'axlMATIC',
      name: 'Axelar Matic',
      icon: 'https://station-assets.terra.money/img/coins/axlMATIC.svg',
      decimals: 18,
      isAxelar: true,
    },
    {
      token: 'uni-wei',
      symbol: 'axlUNI',
      name: 'Axelar Uniswap',
      icon: 'https://station-assets.terra.money/img/coins/axlUNI.svg',
      decimals: 18,
      isAxelar: true,
    },
    {
      token: 'uusdc',
      symbol: 'axlUSDC',
      name: 'Axelar USD Coin',
      icon: 'https://station-assets.terra.money/img/coins/axlUSDC.svg',
      decimals: 6,
      isAxelar: true,
    },
    {
      token: 'uusdt',
      symbol: 'axlUSDT',
      name: 'Axelar USD Tether',
      icon: 'https://station-assets.terra.money/img/coins/axlUSDT.svg',
      decimals: 6,
      isAxelar: true,
    },
    {
      token: 'wbtc-satoshi',
      symbol: 'axlWBTC',
      name: 'Axelar Wrapped Bitcoin',
      icon: 'https://station-assets.terra.money/img/coins/axlWBTC.svg',
      decimals: 8,
      isAxelar: true,
    },
    {
      token: 'weth-wei',
      symbol: 'axlWETH',
      name: 'Axelar Wrapped Ethereum',
      icon: 'https://station-assets.terra.money/img/coins/axlETH.svg',
      decimals: 18,
      isAxelar: true,
    },
    {
      token: 'busd-wei',
      symbol: 'BUSD',
      name: 'Binance USD',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/busd.png',
      decimals: 18,
    },
    {
      token: 'wbnb-wei',
      symbol: 'BNB',
      name: 'Wrapped BNB',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/binancesmartchain/images/wbnb.svg',
      decimals: 18,
    },
    {
      token: 'wavax-wei',
      symbol: 'AVAX',
      name: 'Wrapped AVAX',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/avalanche/images/avax.png',
      decimals: 18,
    },
    {
      token: 'dot-planck',
      symbol: 'DOT',
      name: 'Wrapped Polkadot',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/polkadot/images/dot.svg',
      decimals: 10,
    },
    {
      token: 'frax-wei',
      symbol: 'FRAX',
      name: 'Frax',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/frax.svg',
      decimals: 18,
    },
    {
      token: 'ape-wei',
      symbol: 'APE',
      name: 'ApeCoin',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/ape.svg',
      decimals: 18,
    },
    {
      token: 'axs-wei',
      symbol: 'AXS',
      name: 'Axie Infinity Shard',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/axs.svg',
      decimals: 18,
    },
    {
      token: 'mkr-wei',
      symbol: 'MKR',
      name: 'Maker',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/mkr.svg',
      decimals: 18,
    },
    {
      token: 'rai-wei',
      symbol: 'RAI',
      name: 'Rai Reflex Index',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/rai.svg',
      decimals: 18,
    },
    {
      token: 'shib-wei',
      symbol: 'SHIB',
      name: 'Shiba Inu',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/shib.svg',
      decimals: 18,
    },
    {
      token: 'xcn-wei',
      symbol: 'XCN',
      name: 'Chain',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/xcn.svg',
      decimals: 18,
    },
    {
      token: 'wglmr-wei',
      symbol: 'GLMR',
      name: 'Wrapped Moonbeam',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/moonbeam/images/glmr.svg',
      decimals: 18,
    },
    {
      token: 'wftm-wei',
      symbol: 'FTM',
      name: 'Wrapped FTM',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/fantom/images/ftm.png',
      decimals: 18,
    },
    {
      token: 'polygon-uusdc',
      symbol: 'polygon.USDC',
      name: 'USD Coin from Polygon',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/polygon.usdc.svg',
      decimals: 6,
    },
    {
      token: 'avalanche-uusdc',
      symbol: 'avalanche.USDC',
      name: 'USD Coin from Avalanche',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/avalanche.usdc.svg',
      decimals: 6,
    },
    {
      token: 'wfil-wei',
      symbol: 'axlFIL',
      name: 'Wrapped FIL from Filecoin',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/filecoin/images/wfil.svg',
      decimals: 18,
    },
    {
      token: 'arb-wei',
      symbol: 'ARB',
      name: 'Arbitrum',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/arbitrum/images/arb.svg',
      decimals: 18,
    },
    {
      token: 'pepe-wei',
      symbol: 'PEPE',
      name: 'Pepe',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/pepe.svg',
      decimals: 18,
    },
    {
      token: 'cbeth-wei',
      symbol: 'cbETH',
      name: 'Coinbase Wrapped Staked ETH',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/cbeth.png',
      decimals: 18,
    },
    {
      token: 'reth-wei',
      symbol: 'rETH',
      name: 'Rocket Pool Ether',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/reth.png',
      decimals: 18,
    },
    {
      token: 'sfrxeth-wei',
      symbol: 'sfrxETH',
      name: 'Staked Frax Ether',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/sfrxeth.svg',
      decimals: 18,
    },
    {
      token: 'wsteth-wei',
      symbol: 'wstETH',
      name: 'Wrapped Lido Staked Ether',
      icon: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/_non-cosmos/ethereum/images/wsteth.svg',
      decimals: 18,
    },
  ],
}
