module.exports = {
  chainID: 'crescent-1',
  lcd: 'https://mainnet.crescent.network:1317',
  gasAdjustment: 1.75,
  gasPrices: { ucre: 0.01 },
  prefix: 'cre',
  coinType: '118',
  baseAsset: 'ucre',
  name: 'Crescent',
  icon: process.env.CF_PAGES_URL + '/img/chains/Crescent.svg',
  ibc: {
    fromTerra: 'channel-37',
    toTerra: 'channel-27',
  },
  channels: {
    'phoenix-1': 'channel-27',
    'axelar-dojo-1': 'channel-4',
    'akashnet-2': 'channel-44',
    'comdex-1': 'channel-49',
    'cosmoshub-4': 'channel-1',
    'juno-1': 'channel-3',
    'kaiyo-1': 'channel-42',
    'mars-1': 'channel-35',
    'osmosis-1': 'channel-9',
    'stride-1': 'channel-29',
    'crescent-1': 'channel-65',
  },
  explorer: {
    address: 'https://www.mintscan.io/crescent/account/{}',
    tx: 'https://www.mintscan.io/crescent/txs/{}',
    validator: 'https://www.mintscan.io/crescent/validators/{}',
    block: 'https://www.mintscan.io/crescent/blocks/id/{}',
  },
  tokens: [
    {
      token: 'ucre',
      symbol: 'CRE',
      name: 'Crescent',
      icon: process.env.CF_PAGES_URL + '/img/coins/Crescent.svg',
      decimals: 6,
    },
  ],
}
