module.exports = {
    chainID: 'neutron-1',
    lcd: 'https://lcd-neutron.tfl.foundation',
    gasAdjustment: 1.75,
    gasPrices: { 
      untrn: 0.84,
      'ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9': 0.03,
      'ibc/F082B65C88E4B6D5EF1DB243CDA1D331D002759E938A0F5CD3FFDC5D53B3E349': 0.3,
    },
    prefix: 'neutron',
    coinType: '118',
    baseAsset: 'untrn',
    name: 'Neutron',
    icon: process.env.CF_PAGES_URL + '/img/chains/Neutron.png',
    disabledModules: ['staking', 'gov'],
    channels: {
      'osmosis-1': 'channel-10',
      'stride-1': 'channel-8',
      'axelar-dojo-1': 'channel-2',
      'cosmoshub-4': 'channel-1',
      'mars-1': 'channel-16',
      'kaiyo-1': 'channel-3',
      'phoenix-1': 'channel-25',
      'stargaze-1': 'channel-18',
    },
    icsChannels: {
    },
    explorer: {
      address: 'https://www.mintscan.io/neutron/account/{}',
      tx: 'https://www.mintscan.io/neutron/tx/{}',
      validator: 'https://www.mintscan.io/neutron/validators/{}',
      block: 'https://www.mintscan.io/neutron/blocks/id/{}',
    },
    tokens: [
      {
        token: 'untrn',
        symbol: 'NTRN',
        name: 'Neutron',
        icon: process.env.CF_PAGES_URL + '/img/coins/Neutron.png',
        decimals: 6,
      },
      {
        token: 'uatom',
        symbol: 'ATOM',
        name: 'Cosmos',
        icon: process.env.CF_PAGES_URL + '/img/coins/Cosmos.svg',
        decimals: 6,
      },
      {
        token: 'uusdc',
        symbol: 'USDC',
        name: 'usdc',
        icon: process.env.CF_PAGES_URL + '/img/coins/axlUSDC.svg',
        decimals: 6,
      },
      {
        token: 'factory/neutron1ug740qrkquxzrk2hh29qrlx3sktkfml3je7juusc2te7xmvsscns0n2wry/wstETH',
        symbol: 'wstETH',
        name: 'Wrapped Lido Staked Ether',
        icon: process.env.CF_PAGES_URL + '/img/coins/WstETH.svg',
        decimals: 18,
      },
    ],
  }
  
