module.exports = {
  chainID: 'stargaze-1',
  lcd: 'https://lcd-stargaze.tfl.foundation',
  gasAdjustment: 1.5,
  gasPrices: { ustars: 1 },
  prefix: 'stars',
  coinType: '118',
  baseAsset: 'ustars',
  name: 'Stargaze',
  icon: process.env.CF_PAGES_URL + '/img/chains/Stargaze.svg',
  channels: {
    'phoenix-1': 'channel-266',
    'carbon-1': 'channel-123',
    'crescent-1': 'channel-51',
    'juno-1': 'channel-5',
    'kaiyo-1': 'channel-49',
    'neutron-1': 'channel-191',
    // 'noble-1': 'channel-204',
    'osmosis-1': 'channel-0',
    'stride-1': 'channel-106',
  },
  explorer: {
    address: 'https://www.mintscan.io/stargaze/account/{}',
    tx: 'https://www.mintscan.io/stargaze/txs/{}',
    validator: 'https://www.mintscan.io/stargaze/validators/{}',
    block: 'https://www.mintscan.io/stargaze/blocks/id/{}',
  },
  tokens: [
    {
      token: 'ustars',
      symbol: 'STARS',
      name: 'Stargaze',
      icon: process.env.CF_PAGES_URL + '/img/coins/Stargaze.svg',
      decimals: 6,
    },
    {
      token: 'factory/stars16da2uus9zrsy83h23ur42v3lglg5rmyrpqnju4/dust',
      symbol: 'STRDST',
      name: 'Stardust STRDST',
      icon: process.env.CF_PAGES_URL + '/img/coins/dust.png',
      decimals: 6,
    },
    {
      token: 'factory/stars16da2uus9zrsy83h23ur42v3lglg5rmyrpqnju4/uBRNCH',
      symbol: 'BRNCH',
      name: 'Branch',
      icon: process.env.CF_PAGES_URL + '/img/coins/brnch.png',
      decimals: 6,
    },
    {
      token: 'factory/stars16da2uus9zrsy83h23ur42v3lglg5rmyrpqnju4/mGAZE',
      symbol: 'GAZE',
      name: 'Gaze GAZE',
      icon: process.env.CF_PAGES_URL + '/img/coins/gaze.png',
      decimals: 6,
    },
    {
      token: 'factory/stars16da2uus9zrsy83h23ur42v3lglg5rmyrpqnju4/uOHH',
      symbol: 'OHH',
      name: 'ohhVAULT ohh',
      icon: process.env.CF_PAGES_URL + '/img/coins/ohh.png',
      decimals: 6,
    },
  ],
}
